# Generated by Django 4.1.4 on 2022-12-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FilePathField(path='E:\\PIPING.STRESS')),
            ],
        ),
    ]
